---
title: "evidence2"
output: html_document
date: "2025-05-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load all of the libraries that we'll be using for this project

```{r echo=FALSE}
# BioCManager library installation
#if (!requireNamespace("BiocManager", quietly = TRUE)){
#  install.packages("BiocManager")
#  BiocManager::install("msa")
#  BiocManager::install("DECIPHER")
#  BiocManager::install("phangorn")
#}

# Library loading
library(ade4)
library(ape)
library(adegenet)
library(Biostrings)
library(DECIPHER)
library(ggplot2)
library(reshape2)
library(dplyr)
library(stringr)
library(tidyr)
library(phangorn)
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(msa)

```

Performing sequence loading

```{r}
# List of countries where COVID killed the most people
countries <- c("usa", "china", "india", "france", "germany", "brazil", "south_korea", "japan", "italy", "uk")

# Map the names to DNA String Sets
sequences <- sapply(countries, function(x) readDNAStringSet(paste("./sequences/", x, ".fasta", sep="")))

# Convert to DNABin types
dna_bins <- do.call(c, sapply(sequences, as.DNAbin))

# Labeling and Display
country_titles <- sapply(countries, function(string) str_to_title(str_replace(string, "_", " ")))

# Create a  Dataframe from the Sequences
sequence_frame <- data.frame(
  country_key = countries,
  country_title  = country_titles,
  sequence_length = sapply(sequences, width),
  a_frequency = sapply(sequences, function(seq) letterFrequency(seq, 'A')),
  c_frequency = sapply(sequences, function(seq) letterFrequency(seq, 'C')),
  g_frequency = sapply(sequences, function(seq) letterFrequency(seq, 'G')),
  t_frequency = sapply(sequences, function(seq) letterFrequency(seq, 'T'))
)

# Print Genome Sequence Lengths
print("The sequence lengths for each genome are as follows")
sequence_frame[3]

# Print Genome Sequence Nitrogenous Base Frequencies
print("The frequencies for each base in each genome are as follows:")
sequence_frame[c(4, 5, 6, 7)]

```

Convert to data frame and graph

```{r}
# Plot Frequencies
ggplot(
  data = sequence_frame %>% gather(Frequencies, Frequency, -country_title, -country_key, -sequence_length),
  aes(x = country_title, y = Frequency, fill = Frequencies)
) +
  geom_bar(stat = 'identity', position = 'dodge') +
  xlab("Countries") +
  scale_fill_discrete(
    labels = c(
      "a_frequency" = "Number of A Bases",
      "c_frequency" = "Number of C Bases",
      "g_frequency" = "Number of G Bases",
      "t_frequency" = "Number of T Bases"
  ))

```

```{r}
# Read FASTAs Again but in a Different Format (idealy, this shouldn't be the case but we couldn't find how to do it)
countries <- c("usa", "china", "india", "france", "germany", "brazil", "south_korea", "japan", "italy", "uk")

# Place Sequences into a DNAStringSet
all_sequences <- DNAStringSet()
for (country in countries) {
  file_path <- paste0("./sequences/", country, ".fasta")
  seq <- readDNAStringSet(file_path)
  all_sequences <- c(all_sequences, seq)
}

# Align DNA Sequences
aligned <- AlignSeqs(all_sequences)
dna <- as.matrix(as.DNAbin(aligned))

# Stop if Our Sequences are not Aligned
stopifnot(length(unique(ncol(dna))) == 1)

# DNA Distribution
dna_distro <- dist.dna(dna, model = "TN93")

# Create NJ Tree From DNA Distro
phylotree <- nj(dna_distro)

# Calculate Bootstrapping Values
boots <- boot.phylo(
  phylotree, 
  dna, 
  function(e) root(nj(dist.dna(e, model = "TN93")), 1),
  B = 100,
  quiet = TRUE
)

# Plot our Phylo Tree with Bootstrap Values
myPal <- colorRampPalette(c("red","yellow","green","blue"))
plot(phylotree, cex = 0.6, main = "NJ Tree")
nodelabels(boots, bg = "white", cex = 0.6, col=transp(num2col(boots, col.pal=myPal),.7))  # Red labels for visibility

# Convert our DNA Distribution and Plot it in a Table
adj_matrix <- as.matrix(dna_distro)
table.paint(
  adj_matrix,
  cleg = 0,
  clabel.row = 0.25,
  clabel.col = 0.25
)
```